#extends: ["spectral:oas"]
rules:
  # We always require a summary
  operation-required-fields:
    severity: error
    message: Missing {{property}}at {{path}}
    given: $.paths.*[get,post,patch,put,delete]
    then:
      - field: "summary"
        function: truthy

  # Require 3-part Semantic Versions as the spec versions
  semver:
    severity: error
    recommended: true
    description: Specs should follow semantic versioning
    message: Specs should follow semantic versioning. {{value}} is not a valid version
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+.[0-9]+.[0-9]+)$"