name: Validate Markdown

on:
  push:
    paths:
      - 'docs/**'

jobs:
  markdown-lint:
    name: Markdown Lint CLI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: 'website/docs, api_docs'
          config_file: ".markdownlint.json"