name: Run Spectral against OpenAPI spec
on:
  push:
    paths:
      - 'openapi.yaml'

jobs:
  spectral:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.11
        with:
          file_glob: 'openapi.yaml'