name: Check Wording
on:
  push:
    paths:
    - 'docs/**'

jobs:
  prose:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.0
      with:
        # Optional
        files: '["docs"]'
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
