name: Validate Dockerfile
on:
  push:
    paths:
      - "./Dockerfile"

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: jbergstroem/hadolint-gh-action@master
        with:
          dockerfile: Dockerfile website/Dockerfile
          # ignore warnings (but still fail on errors) from hadolint
          error_level: 1